SESSDATA: "" # SESSDATA,用来伪装登陆信息
download_dir: "./downloads" # 下载后保存的路径

no_danmaku: true # 不下载弹幕。

# 这两个决定能下哪些视频，清晰度，用户有访问哪些视频的权限，就能下哪些视频，
# 比如大会员视频就需要大会员登陆的SESSDATA
# 而无登陆用户最高只能下载480p
login_strict: true # 仅当SESSDATA不为空时生效，严格校验登陆信息是否有效
                   # 如果SESSDATA填写错误，会导致校验失败。
vip_strict: false # 仅当SESSDATA不为空时生效，严格校验大会员，
                  # 如果不是大会员，请设置false,否则会无法下载。
                  # 如果是大会员，请设置true,否则有时候会被当成普通用户拦截。

