chrome_driver: './chromedriver-linux64/chromedriver' # chrome-driver 路径
chrome: './chrome-linux64/chrome' # chrome 路径

# 如果你还没有使用过它们，你可以到这里下载你系统对应的版本:
# https://googlechromelabs.github.io/chrome-for-testing/#stable
# 然后解压，指定正确路径即可

target_url: 'https://www.bilibili.com/'

